# Generated by Django 4.2.11 on 2024-04-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availabel_size',
        ),
        migrations.DeleteModel(
            name='AvailableSize',
        ),
    ]
